export const lightTokens = {
  plain: '#FFFFFF',
  subdued: '#F6F9FC',
  disabledBg: '#ECF1F9',
  hover: 'rgba(23,80,186,0.06)',
  select: '#F1F6FF',
  border: '#E3E8F2',
  borderPlain: '#CAD3E2',
  borderStrong: '#A2B1C9',
  text: '#1D2A3E',
  heading: '#111C2C',
  textSub: '#516381',
  primary: '#0B64DD',
  primaryText: '#1750BA',
  primaryHover: '#0A57BE',
  onPrimary: '#FFFFFF',
  success: '#008A5E',
  successBg: '#E9FFF7',
  successBorder: '#AEE8D2',
  successText: '#09724D',
  warning: '#FACB3D',
  warningBg: '#FFF7E2',
  warningBorder: '#FCD883',
  warningText: '#825803',
  danger: '#C61E25',
  dangerBg: '#FFF3F1',
  dangerBorder: '#FFC9C2',
  dangerText: '#A71627',
  vis0: '#16C5C0',
  vis2: '#61A2FF',
  vis4: '#EE72A6',
  vis6: '#F6726A',
  vis8: '#EAAE01',
  accent: '#BC1E70',
  navBg: '#2B394F',
  navBorder: '#1D2A3E',
  navText: '#FFFFFF',
  navTextSub: '#CAD3E2',
  navHover: 'rgba(255,255,255,0.10)',
  navSelectBg: 'rgba(97,162,255,0.18)',
  navSelectText: '#BFDBFF',
  shadowS: '0 0.7px 1.4px rgba(7,16,31,.07), 0 1.9px 4px rgba(7,16,31,.05)',
}

export const darkTokens = {
  ...lightTokens,
  plain: '#1D1E24',
  subdued: '#16181D',
  disabledBg: '#25262E',
  hover: 'rgba(97,162,255,0.1)',
  select: '#172336',
  border: '#333A47',
  borderPlain: '#444B58',
  borderStrong: '#6A7FA0',
  text: '#DFE5EF',
  heading: '#F5F7FA',
  textSub: '#98A2B3',
  primary: '#61A2FF',
  primaryText: '#61A2FF',
  primaryHover: '#8AB9FF',
  onPrimary: '#07101F',
  success: '#24C292',
  successBg: '#0E2B25',
  successBorder: '#1B5C48',
  successText: '#4DD5AC',
  warning: '#FCD883',
  warningBg: '#332A16',
  warningBorder: '#6B5620',
  warningText: '#F3C55A',
  danger: '#F6726A',
  dangerBg: '#331E1E',
  dangerBorder: '#6E3436',
  dangerText: '#F6726A',
  navBg: '#0F1116',
  navBorder: '#333A47',
  navText: '#F5F7FA',
  navTextSub: '#A2B1C9',
}

export const euiModify = {
  colors: {
    LIGHT: {
      primary: lightTokens.primary,
      accent: lightTokens.accent,
      success: lightTokens.success,
      warning: lightTokens.warning,
      danger: lightTokens.danger,
      textPrimary: lightTokens.primaryText,
      textHeading: lightTokens.heading,
      textParagraph: lightTokens.text,
      textSubdued: lightTokens.textSub,
      textSuccess: lightTokens.successText,
      textWarning: lightTokens.warningText,
      textDanger: lightTokens.dangerText,
      backgroundBasePlain: lightTokens.plain,
      backgroundBaseSubdued: lightTokens.subdued,
      backgroundBaseSuccess: lightTokens.successBg,
      backgroundBaseWarning: lightTokens.warningBg,
      backgroundBaseDanger: lightTokens.dangerBg,
      backgroundBaseInteractiveHover: lightTokens.hover,
      backgroundBaseInteractiveSelect: lightTokens.select,
      body: lightTokens.subdued,
    },
    DARK: {
      primary: darkTokens.primary,
      accent: darkTokens.accent,
      success: darkTokens.success,
      warning: darkTokens.warning,
      danger: darkTokens.danger,
      textPrimary: darkTokens.primaryText,
      textHeading: darkTokens.heading,
      textParagraph: darkTokens.text,
      textSubdued: darkTokens.textSub,
      textSuccess: darkTokens.successText,
      textWarning: darkTokens.warningText,
      textDanger: darkTokens.dangerText,
      backgroundBasePlain: darkTokens.plain,
      backgroundBaseSubdued: darkTokens.subdued,
      backgroundBaseSuccess: darkTokens.successBg,
      backgroundBaseWarning: darkTokens.warningBg,
      backgroundBaseDanger: darkTokens.dangerBg,
      backgroundBaseInteractiveHover: darkTokens.hover,
      backgroundBaseInteractiveSelect: darkTokens.select,
      body: darkTokens.subdued,
    },
  },
}
